### ISSUE TITLE
Feature Request: Add Input to settings

### ISSUE THREAD

**Issue by misterkiem** [shumatech/wiimplay#1]
I'm using my wiim pro to switch between the optical in and wifi casting. If you could expand the audio settings on this app to be able to select the input as well as the output that would be a huge help for me.

I'm not familiar with go or I would do it myself, but since it's just another api endpoint it should hopefully not be too difficult to implement. Thanks!

**Comment by shumatech** [comment]
Added in commit [7b27a98](https://github.com/shumatech/wiimplay/commit/7b27a9880c0948e059e3eb1ed2d0eaeb3343e0d3)
