### ISSUE TITLE
strconv.ParseUint: parsing "": invalid syntax - Wiim Mini

### ISSUE THREAD

**Issue by GraemeWi** [shumatech/wiimplay#2]
App works fine for Wiim Pro, however when pointed to the Wiim mini, in the terminal the following text shows repeatedly - (192.167.1.72 is the IP for the Mini)

2024/09/19 20:03:09 WiiM Play v0.1 (Build: 2024-02-26T10:49:58)
2024/09/19 20:03:09 Connecting to http://192.168.1.72:49152/description.xml
2024/09/19 20:03:09 strconv.ParseUint: parsing "": invalid syntax

In the app no playlists are visable / selectable for the Mini (Pro works fine with playlists visable and selectable)
The player controls do work (pause / previous / next / equalizer etc) all pass to the Mini and have effect. No data shown for now playing / album art etc shows for the Mini while it is playing.

I'll see if I can poke through the source files to figure out what is having trouble parsing, but not familiar with Go

Cheers,
G

**Comment by shumatech** [comment]
I don't have a Mini so I'm unable to troubleshoot it.  From the error message, I would guess that the Mini is returning XML with an empty value for a field defined in the schema as an integer.  You could try running the scan utility included in the repo:
```
$ git clone https://github.com/shumatech/wiimplay.git
$ cd wiimplay/scan
$ go run .
```
Check the output for a failure which could help pinpoint which UPNP call is returning the bad XML.

**Comment by GraemeWi** [comment]
Found the issue at the point of GetInfoEx, and some digging with a UPnP tool show the Mini is returning an additional field 'ScapeLoopMode' that the Pro doesn't return, and the Pro returning 'CurrentMute' that the Mini doesn't return. In the attached screen shot Mini is on the left, Pro on the right
![wiim mini left pro right](https://github.com/user-attachments/assets/951c38cc-4af4-4572-9901-caa991e3d098)

**Comment by shumatech** [comment]
That's good info.  I pushed a fix that should avoid the issue.  It's on the wiim-mini-fix branch if you want to try it out.  Let me know if you want me to attach a binary instead.

**Comment by GraemeWi** [comment]
Many thanks - I was able to compile the new branch, and it works perfectly in the Mini. Thats awesome!
![wiim mini working](https://github.com/user-attachments/assets/2f0293ff-a51f-42f6-b0c6-f98c5d57cf7f)
